### ISSUE TITLE
Update to SRP-6a

### ISSUE THREAD

**Issue by T3chTobi** [falkmueller/srp#1]
Great code, works amazing!

Is it possible to update SRP to the lastest Version SRP-6a? The documentation is here: http://srp.stanford.edu/design.html and http://srp.stanford.edu/srp6.ps

That would be amazing!

Thank you!

**Comment by CodingAnonymous** [comment]
Ich schreibe gerade meine Bachelorarbeit und möchte gerne SRP implementieren. Ich müsste dazu die aktuellere Version SRP-6a nutzen. Ich wäre dir sehr sehr dankbar, wenn das möglich wäre!

**Comment by falkmueller** [comment]
Hi,
I implemended it with k = H(N, g), so it is already the RSP-6a standard.

**Comment by T3chTobi** [comment]
Thank you for your response, that's awesome!

Why did you choose exactly this message order? http://srp.stanford.edu/srp6.ps suggests it is not the optimal order.

In Phase 2 the Client sends M1 to the Server. Shouldn't there be the username "I" attached? When multiple user login at the same time the server doesn't know "who / which user" sent M1.

**Comment by T3chTobi** [comment]
Can (how) $n_base64 be new generated to be different form the public Github repository?
Thank you in advance!

**Comment by falkmueller** [comment]
Hi,

>> In Phase 2 the Client sends M1 to the Server. Shouldn't there be the username "I" attached?
>> When multiple user login at the same time the server doesn't know "who / which user" sent M1.

Each user has its own unique session. The session is a simple php cookie based session, handeled in the ```index.php``` file.

>> Can (how) $n_base64 be new generated to be different form the public Github repository?
>> Thank you in advance!

You can clone the repo and change the code. This Repo is only a example-implementation. So it is actually not configurabel.
